language: python
python:
  - "3.5"
  - "3.6"
cache: pip
before_install:
  - pip3 install pytest pytest-cov
  - pip3 install coveralls
install:
  - pip3 install -r requirements.txt
script:
  - py.test --cov
